### PR TITLE
Feature/panels

### PR DESCRIPTION
**Pull request by chinedu117**
> Creates 3 main panels
> Dark mode logo swap
>

### CODE REVIEW

**Comment by chinedu117** [comment]
@isedwards  Please review.

**Comment by isedwards** [comment]
When I build the docs I see an empty site with the three sections...

On the home page, is it possible to add panels like these for selecting the section?
image

**Comment by chinedu117** [comment]
I will add them now

**Comment by isedwards** [comment]
@chinedu117 I had a few problems with this PR including:
- `conf.py` contained lots of references to the repo that inspired us to change theme (but we don't have permission to directly use their code)
- `requirements.txt` had a lot of extra junk
- The PR includes the shuttle logo image - but there's no information on where it's from or whether other projects could be licenced to use it.

I [started again from scratch](https://github.com/opencdms/docs.opencdms.org/pull/6) and added `pydata-sphinx-theme` and `sphinx-panels` to our empty project. I've used a comparable icon set that we have permission to use.

It's now online here: https://docs.opencdms.org/

**Pull request closed without merging**
